-- AlterTable
ALTER TABLE `notice` MODIFY `type` ENUM('NOTICE', 'PAYMENT_DUE', 'PAYMENT_OVERDUE', 'ABSENT_ALERT', 'CLASS_NOTICE', 'RECEIPT', 'ATTENDANCE_ARRIVAL', 'CLASS_STARTED', 'STUDENT_ARRIVED', 'CLASS_ENDED', 'PAYMENT_REMINDER', 'HOMEWORK_ASSIGNED', 'HOMEWORK_REVIEWED', 'QUIZ_ASSIGNED', 'LIVE_CLASS_REMINDER', 'COURSE_RESOURCE_UPLOADED', 'ENROLLMENT_REQUEST', 'ENROLLMENT_APPROVED', 'ENROLLMENT_REJECTED') NOT NULL DEFAULT 'NOTICE';

-- AlterTable
ALTER TABLE `studentcardhistory` MODIFY `previousStatus` ENUM('PRINT_PENDING', 'PRINTED', 'ACTIVE', 'INACTIVE', 'LOST', 'MISSING', 'STOLEN', 'DAMAGED', 'REPLACED', 'BLOCKED') NULL,
    MODIFY `newStatus` ENUM('PRINT_PENDING', 'PRINTED', 'ACTIVE', 'INACTIVE', 'LOST', 'MISSING', 'STOLEN', 'DAMAGED', 'REPLACED', 'BLOCKED') NULL;
