"use client";
import { useMemo, useState, useTransition } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { BookOpen, Calculator, FlaskConical, History, Laptop, Languages, Loader2, Pencil, Plus, Power, Search, X } from "lucide-react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { saveSubject, setSubjectActive } from "@/app/(dashboard)/subjects/actions";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Select } from "@/components/ui/select"; import { Textarea } from "@/components/ui/textarea";
import { subjectSchema, type SubjectInput } from "@/lib/validations";
type Row={id:string;name:string;description:string|null;color:string;icon:string;isActive:boolean;classes:number;courses:number;homework:number;quizzes:number};
const icons={BookOpen,Calculator,FlaskConical,Laptop,Languages,History};
export function SubjectsManager({subjects}:{subjects:Row[]}){const[q,setQ]=useState("");const[panel,setPanel]=useState<Row|"new"|null>(null);const[pending,startTransition]=useTransition();const filtered=useMemo(()=>subjects.filter(s=>(s.name+" "+(s.description??"")).toLowerCase().includes(q.toLowerCase())),[q,subjects]);return <><div className="space-y-6"><section className="glass-panel rounded-2xl p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Badge variant="secondary">Academic catalog</Badge><h2 className="mt-4 text-3xl font-semibold">Subjects</h2><p className="mt-2 text-sm text-muted-foreground">Subjects organize classes, courses, homework, quizzes, and resources without coupling them together.</p></div><Button onClick={()=>setPanel("new")}><Plus className="h-4 w-4"/>Add subject</Button></div><div className="relative mt-5 max-w-md"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search subjects..."/></div></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(s=>{const Icon=icons[s.icon as keyof typeof icons]??BookOpen;return <Card key={s.id} className="glass-panel"><CardContent className="p-5"><div className="flex justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-xl" style={{background:`${s.color}18`,color:s.color}}><Icon className="h-6 w-6"/></span><Badge variant={s.isActive?"success":"outline"}>{s.isActive?"active":"disabled"}</Badge></div><h3 className="mt-4 text-xl font-semibold">{s.name}</h3><p className="mt-2 line-clamp-2 min-h-10 text-sm text-muted-foreground">{s.description||"No description"}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span className="rounded-lg border p-2">{s.classes} classes</span><span className="rounded-lg border p-2">{s.courses} courses</span></div><div className="mt-4 flex justify-end"><Button variant="ghost" size="icon" onClick={()=>setPanel(s)}><Pencil className="h-4 w-4"/></Button><Button variant="ghost" size="icon" disabled={pending} onClick={()=>startTransition(async()=>{const r=await setSubjectActive(s.id,!s.isActive);r.ok?toast.success(r.message):toast.error(r.message)})}><Power className="h-4 w-4"/></Button></div></CardContent></Card>})}</section></div>{panel?<SubjectPanel row={panel==="new"?null:panel} onClose={()=>setPanel(null)}/>:null}</>}
function SubjectPanel({row,onClose}:{row:Row|null;onClose:()=>void}){const[pending,startTransition]=useTransition();const f=useForm<SubjectInput>({resolver:zodResolver(subjectSchema),defaultValues:row?{name:row.name,description:row.description??"",color:row.color,icon:row.icon,isActive:row.isActive}:{name:"",description:"",color:"#0f766e",icon:"BookOpen",isActive:true}});return <div className="fixed inset-0 z-50 bg-primary/35"><button className="absolute inset-0" onClick={onClose}/><div className="absolute right-0 h-full w-full max-w-xl bg-background p-6 shadow-xl"><div className="flex justify-between"><h2 className="text-2xl font-semibold">{row?"Edit":"Add"} subject</h2><Button size="icon" variant="outline" onClick={onClose}><X className="h-4 w-4"/></Button></div><form className="mt-6 space-y-4" onSubmit={f.handleSubmit(v=>startTransition(async()=>{const r=await saveSubject(row?.id??null,v);if(r.ok){toast.success(r.message);onClose()}else toast.error(r.message)}))}><Input placeholder="Subject name" {...f.register("name")}/><Textarea placeholder="Description" {...f.register("description")}/><div className="grid grid-cols-2 gap-4"><Input type="color" {...f.register("color")}/><Select {...f.register("icon")}>{Object.keys(icons).map(x=><option key={x}>{x}</option>)}</Select></div><label className="flex gap-2"><input type="checkbox" {...f.register("isActive")}/> Active</label><Button className="w-full" disabled={pending}>{pending?<Loader2 className="h-4 w-4 animate-spin"/>:null}Save subject</Button></form></div></div>}
